# Gitpod configuration for Android + Hardhat project

tasks:
  - name: Setup Android, Node, Gradle
    init: |
      set -e

      echo "--- Ensuring essential tools are installed ---"
      sudo apt-get update -y

      # Java 17
      sudo apt-get install -y openjdk-17-jdk
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
      export PATH="$JAVA_HOME/bin:$PATH"

      # Node.js + npm (Ubuntu repo version)
      sudo apt-get install -y nodejs npm

      echo "--- Verifying tool installations ---"
      java -version
      node -v
      npm -v

      echo "--- Setting up project dependencies ---"
      # Hardhat deps
      cd blockchain
      npm install --legacy-peer-deps
      cd ..

      # Android build
      chmod +x android-app/gradlew
      cd android-app
      ./gradlew --no-daemon assembleDebug
      cd ..

      echo "Environment setup complete."
      echo "To build the Android app: cd android-app && ./gradlew assembleDebug"
      echo "To run Hardhat commands: cd blockchain && npx hardhat compile"
    command: |
      echo "Workspace ready. Check the setup task output for build details."

ports:
  - port: 8080
    onOpen: ignore
  - port: 8545
    onOpen: ignore

vscode:
  extensions:
    - esbenp.prettier-vscode
    - mhutchie.git-graph
    - ms-vscode.vscode-typescript-next
    - redhat.java
    - vscjava.vscode-java-test
    - dbaeumer.vscode-eslint
    - beaugunderson.android-dev-ext
    - solc.solidity
    - serayuzgur.crates

image:
  file: .gitpod.Dockerfile
